export const compressibles: {
  readonly '1km': true
  readonly '3gpp': false
  readonly '7z': false
  readonly aac: false
  readonly ac: true
  readonly ai: true
  readonly air: false
  readonly aml: true
  readonly amlx: false
  readonly apk: false
  readonly apng: false
  readonly appcache: true
  readonly appinstaller: false
  readonly appx: false
  readonly appxbundle: false
  readonly arj: false
  readonly atom: true
  readonly atomcat: true
  readonly atomdeleted: true
  readonly atomsvc: true
  readonly au: false
  readonly avif: false
  readonly bdo: true
  readonly bdoc: false
  readonly bin: true
  readonly bmml: true
  readonly bmp: true
  readonly boz: false
  readonly bpk: true
  readonly buffer: true
  readonly bz: false
  readonly bz2: false
  readonly caf: false
  readonly ccxml: true
  readonly cdfx: true
  readonly cdxml: true
  readonly class: false
  readonly conf: true
  readonly cpl: true
  readonly csl: true
  readonly css: true
  readonly csv: true
  readonly dae: true
  readonly dart: true
  readonly davmount: true
  readonly dbk: true
  readonly dcmp: true
  readonly dd2: true
  readonly ddf: true
  readonly dds: true
  readonly deb: true
  readonly def: true
  readonly deploy: true
  readonly dib: true
  readonly dist: true
  readonly distz: true
  readonly dll: true
  readonly dmg: true
  readonly dms: true
  readonly doc: false
  readonly docx: false
  readonly dot: false
  readonly dtb: true
  readonly dtd: true
  readonly dump: true
  readonly dvi: false
  readonly dwd: true
  readonly ear: false
  readonly ecma: true
  readonly elc: true
  readonly eml: true
  readonly emma: true
  readonly emotionml: true
  readonly eot: true
  readonly eps: true
  readonly epub: false
  readonly es3: true
  readonly et3: true
  readonly exe: true
  readonly fdt: true
  readonly flv: false
  readonly fo: true
  readonly gdoc: false
  readonly gdraw: false
  readonly geojson: true
  readonly gform: false
  readonly gif: false
  readonly gjam: false
  readonly glb: true
  readonly glsl: true
  readonly gltf: true
  readonly gmap: false
  readonly gml: true
  readonly gpx: true
  readonly grxml: true
  readonly gscript: false
  readonly gsheet: false
  readonly gsite: false
  readonly gslides: false
  readonly gz: false
  readonly hal: true
  readonly hdd: true
  readonly held: true
  readonly htm: true
  readonly html: true
  readonly ico: true
  readonly iges: false
  readonly igs: false
  readonly img: true
  readonly in: true
  readonly ini: true
  readonly ink: true
  readonly inkml: true
  readonly ipynb: true
  readonly irp: true
  readonly iso: true
  readonly its: true
  readonly jar: false
  readonly jfif: false
  readonly jnlp: false
  readonly jp2: false
  readonly jpe: false
  readonly jpeg: false
  readonly jpf: false
  readonly jpg: false
  readonly jpg2: false
  readonly jpgm: false
  readonly jpm: false
  readonly jpx: false
  readonly js: true
  readonly json: true
  readonly jsonld: true
  readonly jsonml: true
  readonly jsx: true
  readonly kml: true
  readonly kmz: false
  readonly lasxml: true
  readonly latex: false
  readonly lbe: true
  readonly less: true
  readonly lgr: true
  readonly link66: true
  readonly list: true
  readonly log: true
  readonly lostxml: true
  readonly lrf: true
  readonly m1v: false
  readonly m2a: false
  readonly m2v: false
  readonly m3a: false
  readonly m4a: false
  readonly m4b: false
  readonly mads: true
  readonly maei: true
  readonly manifest: true
  readonly map: true
  readonly mar: true
  readonly markdown: true
  readonly mathml: true
  readonly md: true
  readonly mdx: true
  readonly mesh: false
  readonly meta4: true
  readonly metalink: true
  readonly mets: true
  readonly mht: true
  readonly mhtml: true
  readonly mime: true
  readonly mjs: true
  readonly mk3d: false
  readonly mkd: true
  readonly mks: false
  readonly mkv: false
  readonly mods: true
  readonly mov: false
  readonly mp2: false
  readonly mp2a: false
  readonly mp3: false
  readonly mp4: false
  readonly mp4a: false
  readonly mp4v: false
  readonly mpd: true
  readonly mpe: false
  readonly mpeg: false
  readonly mpf: true
  readonly mpg: false
  readonly mpg4: false
  readonly mpga: false
  readonly mpkg: true
  readonly mpp: true
  readonly mrcx: true
  readonly mscml: true
  readonly msg: false
  readonly msh: false
  readonly msi: true
  readonly msix: false
  readonly msixbundle: false
  readonly msm: true
  readonly msp: true
  readonly musd: true
  readonly musicxml: true
  readonly mxml: true
  readonly n3: true
  readonly ncx: true
  readonly obgx: true
  readonly odg: false
  readonly odp: false
  readonly ods: false
  readonly odt: false
  readonly oga: false
  readonly ogg: false
  readonly ogv: false
  readonly ogx: false
  readonly omdoc: true
  readonly opf: true
  readonly opus: false
  readonly org: true
  readonly osfpvg: true
  readonly osm: true
  readonly otf: true
  readonly ova: true
  readonly ovf: true
  readonly owl: true
  readonly p12: false
  readonly pac: true
  readonly pde: true
  readonly pdf: false
  readonly pfx: false
  readonly pgp: false
  readonly php: true
  readonly pkg: true
  readonly pkpass: false
  readonly pls: true
  readonly ply: true
  readonly png: false
  readonly pot: false
  readonly pps: false
  readonly ppt: false
  readonly pptx: false
  readonly provx: true
  readonly ps: true
  readonly psd: true
  readonly pskcxml: true
  readonly qt: false
  readonly raml: true
  readonly rapd: true
  readonly rar: false
  readonly rdf: true
  readonly relo: true
  readonly res: true
  readonly rif: true
  readonly rl: true
  readonly rld: true
  readonly rng: true
  readonly rs: true
  readonly rsat: true
  readonly rsd: true
  readonly rsheet: true
  readonly rss: true
  readonly rtf: true
  readonly rtx: true
  readonly rusd: true
  readonly sbml: true
  readonly sdkd: true
  readonly sdkm: true
  readonly senmlx: true
  readonly sensmlx: true
  readonly ser: false
  readonly sh: true
  readonly shader: true
  readonly shf: true
  readonly shtml: true
  readonly silo: false
  readonly sit: false
  readonly sls: true
  readonly smi: true
  readonly smil: true
  readonly snd: false
  readonly so: true
  readonly spx: false
  readonly sru: true
  readonly srx: true
  readonly ssdl: true
  readonly ssml: true
  readonly stpx: true
  readonly stpxz: false
  readonly stpz: false
  readonly svg: true
  readonly svgz: true
  readonly swf: false
  readonly swidtag: true
  readonly tar: true
  readonly td: true
  readonly tei: true
  readonly teicorpus: true
  readonly text: true
  readonly tfi: true
  readonly tif: false
  readonly tiff: false
  readonly toml: true
  readonly tsv: true
  readonly ttf: true
  readonly ttml: true
  readonly txt: true
  readonly ubj: false
  readonly uo: true
  readonly uoml: true
  readonly uri: true
  readonly uris: true
  readonly urls: true
  readonly usdz: false
  readonly uvt: true
  readonly uvvt: true
  readonly vbox: true
  readonly 'vbox-extpack': false
  readonly vcard: true
  readonly vdi: true
  readonly vhd: true
  readonly vmdk: true
  readonly vrml: false
  readonly vtt: true
  readonly vxml: true
  readonly wadl: true
  readonly war: false
  readonly wasm: true
  readonly wav: false
  readonly wbs: true
  readonly weba: false
  readonly webapp: true
  readonly webm: false
  readonly webmanifest: true
  readonly wif: true
  readonly wmv: false
  readonly wrl: false
  readonly wsdl: true
  readonly wspolicy: true
  readonly x3d: true
  readonly x3db: false
  readonly x3dbz: false
  readonly x3dv: false
  readonly x3dvz: false
  readonly x3dz: true
  readonly xaml: true
  readonly xav: true
  readonly xca: true
  readonly xcs: true
  readonly xdcf: true
  readonly xdf: true
  readonly xdm: true
  readonly xdp: true
  readonly xdssc: true
  readonly xel: true
  readonly xenc: true
  readonly xer: true
  readonly xht: true
  readonly xhtm: true
  readonly xhtml: true
  readonly xhvml: true
  readonly xla: false
  readonly xlc: false
  readonly xlf: true
  readonly xlm: false
  readonly xls: false
  readonly xlsx: false
  readonly xlt: false
  readonly xlw: false
  readonly xml: true
  readonly xns: true
  readonly xop: true
  readonly xpi: false
  readonly xpl: true
  readonly xps: false
  readonly xsd: true
  readonly xsf: true
  readonly xsl: true
  readonly xslt: true
  readonly xsm: true
  readonly xspf: true
  readonly xul: true
  readonly xvm: true
  readonly xvml: true
  readonly yaml: true
  readonly yin: true
  readonly yml: true
  readonly ymp: true
  readonly zaz: true
  readonly zip: false
  readonly zmm: true
}
